# Аннотация {.unnumbered .unlisted}

Данная выпускная квалификационная работа посвящена анализу и верификации эпидемиологической модели распространения компьютерного вируса SEIRS-NIMFA в сетях передачи данных. В работе представлен теоретический обзор классических эпидемиологических моделей: SIR, SEIR и SEIRS, которые широко применяются для моделирования распространения инфекционных заболеваний. Подробно рассмотрена математическая модель SEIRS-NIMFA, программная реализация которой выполнена с использованием языка Python. Для верификации модели построена топология сети и проведен натурный эксперимент в двух инструментах моделирования: Kathará и Containerlab. В качестве основного метода распространения вредоносного трафика используется принцип действия червя Морриса, заключающийся в самокопировании компьютерного вируса и передачи по сети. Результаты моделирования анализируются с помощью сравнения графиков динамики заражения. Полученные выводы демонстрируют согласованность между математической моделью и практическими симуляциями, подтверждая адекватность модели SEIRS-NIMFA для описания процессов распространения вредоносного ПО в сетевых средах.

Практическая значимость данной работы заключается в возможности применения предложенного подхода к решению задач кибербезопасности и разработке механизмов защиты. Актуальность исследования обусловлена ​​растущим числом киберугроз и необходимостью в точных и масштабируемых инструментах моделирования динамики заражения сети.
