# Инструментарий для натурного моделирования

## Kathará

Kathará -- это легковесное средство эмуляции сети с открытым исходным кодом, поддерживаемое на основных операционных системах (Linux, macOs, Windows) [@Scazzariello2020].

Kathará предоставляет доступ к моделированию устройств, которые по умолчанию используют Docker-образ. Устройства можно настроить с произвольным количеством виртуальных сетевых интерфейсов, эмулируется процессор, оперативная память и дисковое пространство.

Для моделирования сетевой топологии в Kathará используется каталог, содержащий файлы конфигурации устройств, а также всей топологии. Файлы конфигурации имеют расширение .startup и представляют собой bash-скрипты инициализации узлов, например: задание ip-адреса интерфейсу, добавление шлюза, настройка ssh. Файл топологии имеет название lab.conf и описывает контейнеры и их подключение к виртуальным сетям.

Архитектура Kathará построена на основе CLI, парсер, менеджер (рис. [-@fig-kathara-architecture]) [@Bonofiglio2018].

```{mermaid}
%%| label: fig-kathara-architecture
%%| fig-cap: "Архитектура Kathará"
%%| fig-width: 6

flowchart LR
    subgraph Kathará
        CLI["CLI-интерфейс<br/>l- команды<br/>v- команды"]
        M["Менеджер"]
        P["Парсер"]

        CLI -->|  | M
        CLI <--> P
    end

    V["Технологии<br/>виртуализации<br/>(Docker, LXC, ...)"]

    M --> V
```

```{mermaid}
graph TD
    A[(Network A)]

    subgraph Hosts
        pc1((pc1))
        pc2((pc2))
        pc3((pc3))
        pc4((pc4))
        pc5((pc5))
        dots["..."]
        pc100((pc100))
    end

    pc1 --- A
    pc2 --- A
    pc3 --- A
    pc4 --- A
    pc5 --- A
    pc100 --- A
```

Kathará предоставляет CLI (Command Line Interface) для управления модулями. Команды делятся на две категории:

- с префиксом v- (vstart, vclean, vconfig). Позволяют запускать отдельные устройства, обеспечивая детальный контроль над их конфигурацией;
- с префиксом l- (lstart, lclean, linfo, lrestart, lconfig). Используются для запуска, остановки, конфигурации эксперимента;

Парсер отвечает за создание объектов системы на основе файлов конфигурации. Он используется как посредник между сетевым сценарием и менеджером. При необходимости парсер можно расширить, добавив поддержку новых форматов конфигурационных файлов, преобразующих саму конфигурацию в доменный объект Kathará. Менеджер, получая объекты, преобразует их формат конкретной виртуализации (Docker, LXC и т.д.). Так как менеджеры - это компоненты, которые реализуют один и тот же интерфейс, такой подход позволяет легко поддерживать несколько технологий виртуализации.

## Containerlab

Containerlab -- это сетевой эмулятор, предоставляющий интерфейс командной строки для оркестрации и управления сетевыми лабораториями на основе контейнеров. Он запускает контейнеры, создает виртуальные соединения между ними и управляет жизненным циклом эмуляции [@ContainerlabDev].

Обычные инструменты оркестрации контейнеров, например, docker-compose, не позволяют пользователю с легкостью создавать связи между контейнерами, что является важной частью топологии сети.

Containerlab решает эту проблему и предоставляет интерфейс CLI для управления сетевыми лабораториями. Пользователю достаточно описать топологию сети в YAML-файле, после чего Containerlab автоматически создаёт контейнеры и настраивает виртуальные соединения между ними. Containerlab поддерживает различные образы контейнеров, включая образы сетевых устройств от таких производителей, как Cisco, Juniper и Arista.

Containerlab позволяет моделировать два вида сетевых топологий: CLOS (рис. [-@fig-clos-topology]) и Arbitrary (рис. [-@fig-arbitrary-topology]).

```{mermaid}
%%| label: fig-clos-topology
%%| fig-cap: "Пример CLOS-топологии сети с уровнями super-spine, spine и leaf"
%%| fig-width: 6

flowchart TB

%% --- rows
subgraph R1["Super Spine"]
direction LR
SS1["SS1"]
SS2["SS2"]
end

subgraph R2["Spine"]
direction LR
S1["S1"]
S2["S2"]
S3["S3"]
S4["S4"]
end

subgraph R3["Leaf"]
direction LR
L1["L1"]
L2["L2"]
L3["L3"]
L4["L4"]
end

%% --- super spine to spine
SS1 --- S1
SS1 --- S2
SS1 --- S3
SS1 --- S4

SS2 --- S1
SS2 --- S2
SS2 --- S3
SS2 --- S4

%% --- spine to leaf, symmetric pattern
S1 --- L1
S1 --- L2

S2 --- L1
S2 --- L2

S3 --- L3
S3 --- L4

S4 --- L3
S4 --- L4
```

```{mermaid}
%%| label: fig-arbitrary-topology
%%| fig-cap: "Пример произвольно соединённой топологии с узлами SR Linux и Arista cEOS"
%%| fig-width: 6

flowchart TB

subgraph ROW1[" "]
direction LR
SR1["SR Linux"]
SPACE1[" "]
SR2["SR Linux"]
end

subgraph ROW2[" "]
direction LR
SR3["SR Linux"]
CEOS["Arista cEOS"]
SR4["SR Linux"]
end

SR1 --- SR3
SR2 --- CEOS
SR2 --- CEOS
CEOS --- SR4

style SPACE1 fill:none,stroke:none,color:none
style ROW1 fill:none,stroke:none
style ROW2 fill:none,stroke:none
```

Сеть CLOS, также известная как архитектура leaf-spine, впервые была описана Чарльзом Клозом в 1953 году и представляет собой многоуровневую коммутационную сеть. Она состоит из трех уровней:

1. Super spine - самый верхний уровень, который обеспечивает связь между разными частями сети.
2. Spine - средний уровень, который обеспечивает высокую пропускную способность.
3. Leaf - самый нижний уровень, который подключается к конечным устройствам, таким как серверы, виртуальные машины и контейнеры.

При этом каждый leaf подключён ко всем spine, а каждый spine в свою очередь подключён ко всем super-spine. Такая топология обеспечивает высокую пропускную способность и отказоустойчивость системы, что делает её популярной в центрах обработки данных.

Arbitrary топология - произвольная топология сети без заранее определенной структуры. В этом случае пользователь может создавать любые соединения между контейнерами, что позволяет моделировать более сложные и нестандартные сетевые сценарии.

Таким образом, Containerlab предоставляет единый интерфейс IaC для управления лабораториями, которые могут включать все необходимые типы узлов.  

## Сравнение средств моделирования

Для сравнения инструментов определим место обоих инструментов в пространстве существующих решений для сетевой эмуляции [@Beuran2012].

По критерию доступности и условиям распространения Kathará и Containerlab относятся к категории свободно распространяемых программных эмуляторов с открытым исходным кодом. Kathará распространяется под лицензией GPLv2, ContainerLab -- под Apache 2.0. Таким образом, их нельзя отнести к коммерческим аппаратным эмулятором. По данному критерию оба инструменты схожи, например, с GNS3, однако архитектурно инструменты сопоставить нельзя.

По способу технической реализации оба инструмента являются программными эмуляторами, функционирующими на стандартном Linux-хосте. Kathará и Containerlab опираются на технологию контейнеризации Docker. Каждый узел виртуальной сети представляет собой отдельный Docker-контейнер, изолированный от остальных с помощью механизма Linux namespaces, то есть каждый узел имеет свое пространство имен и не конфликтует с другими узлами сети. Это архитектурное решение влияет на характеристики средств моделирования. В отличие от аппаратных эмуляторов, например, Cisco Packet Tracer, производительность программных эмуляторов ограничены возможностями хост-машины.

По уровню эмуляции оба инструмента реализуют эмуляцию топологического уровня. Виртуальная инфрастуктура задается пользовательским описанием топологии сети с указанием узлов, их типов и связей между ними. Следовательно, эмуляторы не работают на уровне отдельного канала как, например, NetEm.

Kathará и Containerlab способны воспроизводить сложные сетевые топологии с реальными протоколами, но не воссоздают физически точное моделирование с учетом параметров конкретного оборудования или характеристик беспроводной среды.  Оба инструмента практически применимы на стандартном исследовательском или учебном оборудовании.

В пространстве существующих сетевых эмуляторов инструменты можно отнести к одной категории средств моделирования, так как различия между ними проявляются не в архитектурном подходе, а в поддерживаемых компонентах и сценариях.

В контексте сетевой эмуляции под реалистичностью понимается точность воспроизведения реального поведения сетевых устройств и протоколов передачи данных. Чем ближе эмулируемая среда к реальной, тем меньше контроля экспериментатор имеет над её параметрами [@Lai2021]. Оба инструмента обеспечивают сопоставимый уровень реалистичности для базовых сценариев. Поведение протоколов передачи данных в эмулируемой среде идентично его поведению на реальном оборудовании, поскольку используется один и тот же программный код.

Различия между инструментами проявляются в поддерживаемых сценариев и в многообразии доступных образов. Kathará по умолчанию использует образ на основе FRRouting -- программного пакета маршрутизации с открытым исходным кодом, поддерживающего протоколы OSPF, BGP, RIP, IS-IS и ряд других. ContainerLab поддерживает образы коммерческих сетевых операционных систем, чем расширяет возможности для воспроизведения сетевых сценариев. Среди официально поддерживаемых платформ — Nokia SR Linux, Arista cEOS, Cisco XRd, Juniper vQFX, VyOS и ряд других. Однако использование образов коммерческих NOS, как правило, требует отдельного лицензирования. 

Масштабируемость в контексте сетевой эмуляции определяется как способность инструмента поддерживать эксперименты с нарастающим числом узлов без принципиального изменения архитектуры или недопустимого снижения производительности. Масштабируемость Kathará ограничена ресурсами единственного хоста, так как инструмент развёртывает топологии в централизованном режиме на одной машине. При такой архитектуре централизованной эмуляции производительность системы существенно деградирует при превышении определенного порога. Containerlab реализует более эффективный механизм управления жизненным циклом контейнеров и распределением ресурсов, что позволяет ему устойчиво работать с топологиями значительно большего масштаба. Containerlab также обеспечивает более быстрое развёртывание при равном числе узлов за счёт параллелизации операций создания контейнеров и оптимизированного взаимодействия с Docker API.

В Kathará топология сети описывается двумя типами файлов: файл lab.conf определяет узлы сети и связи между ними, файлы с расширением .startup содержат команды инициализации каждого узла, выполняемые при его запуске. Описание сценария интуитивно понятно и не требует знаний о системах контейнеризации. Containerlab применяет иной подход к описанию топологии: конфигурация определяется в YAML-файле, структура которого строго типизирована и поддаётся автоматической валидации.

Таким образом, ключевое различие между инструментами заключается в вариативности сетевых сценариев и сложности использования, что влияет на области применения эмуляторов. Kathará ориентирована на моделирование сетевых сценариев и проведение академических экспериментов, тогда как Containerlab предназначен для практического тестирования и отладки сетевых конфигураций в условиях, близких к реальной эксплуатации.