# Заключение {.unnumbered}

В выпускной квалификационной работе были теоретически рассмотрены эпидемиологические модели семейства SIR, выбран подход к их моделированию и программно реализован эксперимент распространения компьютерного вируса. Для проведения эксперимента была использована модель SEIRS-NIMFA, в которой вероятность заражения каждого узла сети определяется степенью зараженности соседних узлов. Эксперимент был проведен с использованием средств натурного моделирования Kathará и Containerlab, обзор и установка которых представлены во второй и третьей главе соответственно. Для программной реализации в Python был применен принцип самокопирования компьютерного червя, а также описана топология сети, состоящая из ста узлов и формирующая собой полносвязный граф.  Исходя из полученных метрик, были построены графики переходов состояний с течением времени в обоих средствах эмуляции. Как в Kathará, так и в Containerlab заметна двухфазная динамика, где наблюдаются быстрый рост числа узлов в состояние Exposed на начальном этапе, а после инкубационного периода - стремительный переход в состояние болезни. Данная закономерность также была отражена в работах, посвященных компартментной эпидемиологической модели SEIRS-NIMFA. Следовательно, результаты эксперимента в обоих средствах моделирования оказались сопоставимы и доказали соответствие теоретической модели.

Таким образом, были достигнуты все поставленные задачи в начале работы:

- Теоретически изучены эпидемиологическая модель SEIRS-NIMFA и компьютерный червь Морриса.
- Проанализированы средства натурного моделирования: Kathará и Containerlab.
- Построена натурная модель в средствах моделирования.
- Проведено сравнение результатов моделирования распространения компьютерного червя.