# Введение {.unnumbered}

Данная работа посвящена исследованию средств натурного моделирования на примере распространения компьютерного вируса. В работе анализируются и сравниваются два эмулятора: Kathará и Containerlab. Для изучения характеристик средств моделирования рассматриваются эпидемиологическая модель SEIRS-NIMFA и компьютерный червь Морриса.

## Актуальность работы {.unnumbered}

Актуальность данной работы обусловлена отсутствием единого исследования, рассматривающего оба средства моделирования. Эта научная работа направлена на заполнение данного пробела знаний эмпирическим путем.

С помощью проведения эксперимента по распространению компьютерного вируса будут выявлены отличительные характеристики эмуляторов, что поможет сформулировать вывод о релевантности их использования для решения исследовательских задач и даст понимание о возможностях и ограничениях рассматриваемых средств натурного моделирования.

## Цель работы {.unnumbered}

Целью выпускной квалификационной работы является исследование распространение компьютерного червя с помощью средств натурного моделирования.

## Задачи работы {.unnumbered}

Основными задачами работы являются:

1. Анализ средств натурного моделирования: Kathará и Containerlab.
2. Теоретическое изучение эпидемиологической модели SEIRS-NIMFA и компьютерного червя Морриса.
3. Обзор алгоритмов для моделирования распространения компьютерного вируса в выбранных эмуляторах.
4. Построение натурной модели в средствах моделирования.

## Методы исследования {.unnumbered}

Методами исследования является изучение и анализ научной литературы по теме, а также создание и проведение воспроизводимого эксперимента распространения вируса.

## Структура работы {.unnumbered}

Работа состоит из введения, трех разделов, заключения и списка используемой литературы. 

Во введении раскрыта суть рассматриваемой проблемы, обоснована актуальность темы, сформулированы цели и задачи, определены методы исследования.

В первом разделе описывается объект исследования, эпидемиологическая модель и компьютерный червь Морриса. На основе изученной теории определен подход к исследованию.

Во втором разделе теоретически рассматриваются и сопоставляются средства эмуляции Kathará и Containerlab.

В третьем разделе описаны параметры установки средств моделирования и выполнена программная реализация эксперимента. Проведен сравнительный анализ результатов с последующим обсуждением.

В заключении подведены общие итоги выпускной квалификационной работы, изложены основные выводы.
